#!/bin/bash

# Remove files installed in postinst
rm -f /etc/opt/chrome/native-messaging-hosts/org.hwcrypto.native.json
test -d /etc/opt/chrome/native-messaging-hosts && rmdir -p --ignore-fail-on-non-empty /etc/opt/chrome/native-messaging-hosts

rm -f /etc/opt/chrome/policies/managed/com.web-eid.policy.json
test -d /etc/opt/chrome/policies/managed && rmdir -p --ignore-fail-on-non-empty /etc/opt/chrome/policies/managed

exit 0
